### ISSUE TITLE
新的报错

### ISSUE THREAD

**Issue by shuijinliuxi** [YaoZeyuan/ZhihuHelp__Python#19]
'NoneType' object has no attribute 'img'

**Comment by YaoZeyuan** [comment]
ok，正在改

**Comment by YaoZeyuan** [comment]
ok，修复了已经，久等了：）

**Comment by shuijinliuxi** [comment]
刚刚试了一下，有以下错误并终止：

Traceback (most recent call last):
  File "zhihuHelp.py", line 15, in <module>
    helper.start()
  File "/Users/oyc/Desktop/zhihuhelp1.7.2/codes/main.py", line 118, in start
    self.addEpubContent(urlInfo['filter'].getResult())
  File "/Users/oyc/Desktop/zhihuhelp1.7.2/codes/simpleFilter.py", line 270, in getResult
    questionPackage = self.addAnswerTo(questionPackage, answerHref)
  File "/Users/oyc/Desktop/zhihuhelp1.7.2/codes/simpleFilter.py", line 163, in addAnswerTo
    answerDict['updateDate'] = self.str2Date(answer[9])
  File "/Users/oyc/Desktop/zhihuhelp1.7.2/codes/simpleFilter.py", line 95, in str2Date
    return datetime.datetime.strptime(date, '%Y-%m-%d')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '\xe7\xbc\x96\xe8\xbe\x91\xe4\xba\x8e 15:05' does not match format '%Y-%m-%d'

**Comment by shuijinliuxi** [comment]
还有一个问题，就是新版本在输入：
python zhihuHelp.py 后不管当前是否最新版本，都会有下面这个流程：
检查更新。。。
发现新版本，
更新说明:
更新日期:2015-11-20 ，点按回车进入更新页面
新版本下载地址:http://www.dwz.cn/helperupgrade

我更新到最新版本的后，总得按下Enter跳转过去后才能继续
